config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :reminders
  root to: "reminders#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/reminder.rb
class Reminder < ApplicationRecord
  attr_accessor :day_rule, :month, :year, :hour, :minute
  belongs_to :user
  validate :input_day, :in_future, if: :input_date
  validates :title, :text, :month, :year, :hour, :minute, presence: true

  VALID_DATE_RULES = [
      'of month',
      'last of month'
  ].freeze


  def parse_date
    self.remind_on = DateTime.new(year.to_i,
                                  month.to_i,
                                  parse_day,
                                  hour.to_i,
                                  minute.to_i,
                                  0,
                                  Time.now.zone)
  end

  private

  def input_day
    valid_input = VALID_DATE_RULES.map do |rule|
      day_rule.include?(rule)
    end
    errors.add :day_rule, 'is invalid' unless valid_input.include?(true)
  end

  def in_future
    errors.add :day_rule, 'is in the past' if parse_date.to_time <= Time.now
  end

  def input_date
    begin
      Date.new(year.to_i, month.to_i, parse_day)
    rescue StandardError
      errors.add :day_rule, 'date invalid'
      return false
    end
  end

  def parse_day
    day = day_rule.split(/\W+/)[0].to_i
    return calculate_day(day) if day_rule.include?('last')

    day
  end

  def calculate_day(day)
    Time.days_in_month(month.to_i, year.to_i) - subtract_day(day)
  end

  def subtract_day(day)
    day.zero? ? day : day - 1
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/reminders_controller.rb
class RemindersController < ApplicationController
  before_action :authenticate_user!, :reminders_facade
  delegate :index, to: :reminders_facade

  def reminders_facade
    @facade = RemindersFacade.new(params,current_user)
  end

  def create
    if reminders_facade.create
      redirect_to reminders_facade.reminder, notice: 'Reminder created'
    else
      render :new
    end
  end

  def destroy
    if reminders_facade.destroy
      redirect_to reminders_url, notice: 'Reminder was successfully destroyed.'
    else
      render :destroy
    end
  end

  def update
    if reminders_facade.update
      redirect_to reminders_facade.reminder, notice: 'Reminder was successfully updated.'
    else
      render :edit
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/reminders_helper.rb
module RemindersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ReminderApp</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
<%= yield %>
<%if current_user %>
  |
  <%= link_to 'Logout', destroy_user_session_path, method: :delete %>
  </br>
  User email:
  <%= current_user.email %>
<%end %>
</body>
</html>

app/views/reminders/_form.html.erb
<%= form_for(@facade.reminder) do |f| %>
  <% if @facade.reminder.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@facade.reminder.errors.count, "error") %> prohibited this reminder from being saved:</h2>

      <ul>
        <% @facade.reminder.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :text %>
    <%= f.text_field :text %>
  </div>

  <div class="field">
    <%= label_tag 'Remind on:' %>
    <%= select_hour(Time.now, field_name: :hour, prefix: :reminder) %>
    <%= select_minute(Time.now, field_name: :minute, prefix: :reminder) %>
    <%= label_tag 'Day:' %>
    <%= f.select :day_rule, options_for_select(@facade.reminder_decorator.day_rule)%>
    </br>
    <%= select_month(Date.today, field_name: :month, prefix: :reminder ) %>
    <%= select_year(Date.today, field_name: :year, prefix: :reminder) %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/reminders/edit.html.erb
<h1>Editing Reminder</h1>

<%= render 'form', reminder: @facade.reminder %>

<%= link_to 'Show', @facade.reminder %> |
<%= link_to 'List', reminders_path %>

app/views/reminders/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Reminders</h1>

<table>
  <thead>
  <tr>
    <th>Title</th>
    <th>Text</th>
    <th>Remind on</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @facade.reminders.each do |reminder| %>
    <tr>
      <td><%= reminder.title %></td>
      <td><%= reminder.text %></td>
      <td><%= reminder.remind_on %></td>
      <td><%= link_to 'Show', reminder %></td>
      <td><%= link_to 'Edit', edit_reminder_path(reminder) %></td>
      <td><%= link_to 'Destroy', reminder, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
  </tbody>

</table>

<br>

<%= link_to 'New Reminder', new_reminder_path %>

app/views/reminders/new.html.erb
<h1>New Reminder</h1>

<%= render 'form', reminder: @facade.reminder %>

<%= link_to 'List', reminders_path %>

app/views/reminders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @facade.reminder.title %>
</p>

<p>
  <strong>Text:</strong>
  <%= @facade.reminder.text %>
</p>

<p>
  <strong>Remind on:</strong>
  <%= @facade.reminder.remind_on %>
</p>

<%= link_to 'Edit', edit_reminder_path(@facade.reminder.id) %> |
<%= link_to 'List', reminders_path %>